// Country properties without geometry, generated from
// public/data/countries-enriched.geojson, with UN subregions from the
// `world-countries` package and capital coordinates from Wikidata.
//
// Capital coordinates matter for street imagery: Mapillary caps a search box at
// 0.01 degrees (~1km), and a country centroid is often rural, desert, or open
// ocean. Sri Lanka's centroid is ~120km from Colombo.

export type CountryInfo = {
  iso2: string;
  name: string;
  continent: string;
  /** UN subregion slug, e.g. southern-asia. Empty when unknown. */
  subregion: string;
  capital: string;
  /** Country centroid — used to place the globe camera. */
  lat: number;
  lng: number;
  /** Capital city coordinates; falls back to the centroid when unknown. */
  capitalLat: number;
  capitalLng: number;
  languages: string[];
};

export const COUNTRY_INDEX: CountryInfo[] = [
  { iso2: "AE", name: "United Arab Emirates", continent: "Asia", subregion: "western-asia", capital: "Abu Dhabi", lat: 24, lng: 54, capitalLat: 24.4511, capitalLng: 54.3969, languages: ["Arabic"] },
  { iso2: "AF", name: "Afghanistan", continent: "Asia", subregion: "southern-asia", capital: "Kabul", lat: 33, lng: 65, capitalLat: 34.5328, capitalLng: 69.1658, languages: ["Dari","Pashto","Turkmen"] },
  { iso2: "AL", name: "Albania", continent: "Europe", subregion: "southeast-europe", capital: "Tirana", lat: 41, lng: 20, capitalLat: 41.3283, capitalLng: 19.8181, languages: ["Albanian"] },
  { iso2: "AM", name: "Armenia", continent: "Asia", subregion: "western-asia", capital: "Yerevan", lat: 40, lng: 45, capitalLat: 40.1814, capitalLng: 44.5144, languages: ["Armenian"] },
  { iso2: "AO", name: "Angola", continent: "Africa", subregion: "middle-africa", capital: "Luanda", lat: -12.5, lng: 18.5, capitalLat: -8.8383, capitalLng: 13.2344, languages: ["Portuguese"] },
  { iso2: "AQ", name: "Antarctica", continent: "Antarctica", subregion: "", capital: "Antarctica", lat: -90, lng: 0, capitalLat: -90, capitalLng: 0, languages: [] },
  { iso2: "AR", name: "Argentina", continent: "South America", subregion: "south-america", capital: "Buenos Aires", lat: -34, lng: -64, capitalLat: -34.5997, capitalLng: -58.3819, languages: ["Guaraní","Spanish"] },
  { iso2: "AT", name: "Austria", continent: "Europe", subregion: "central-europe", capital: "Vienna", lat: 47.33333333, lng: 13.33333333, capitalLat: 48.2083, capitalLng: 16.3725, languages: ["Austro-Bavarian German"] },
  { iso2: "AU", name: "Australia", continent: "Oceania", subregion: "australia-and-new-zealand", capital: "Canberra", lat: -27, lng: 133, capitalLat: -35.2931, capitalLng: 149.1269, languages: ["English"] },
  { iso2: "AZ", name: "Azerbaijan", continent: "Asia", subregion: "western-asia", capital: "Baku", lat: 40.5, lng: 47.5, capitalLat: 40.3667, capitalLng: 49.8352, languages: ["Azerbaijani","Russian"] },
  { iso2: "BA", name: "Bosnia and Herz.", continent: "Europe", subregion: "southeast-europe", capital: "Sarajevo", lat: 44, lng: 18, capitalLat: 43.8564, capitalLng: 18.4131, languages: ["Bosnian","Croatian","Serbian"] },
  { iso2: "BD", name: "Bangladesh", continent: "Asia", subregion: "southern-asia", capital: "Dhaka", lat: 24, lng: 90, capitalLat: 23.7289, capitalLng: 90.3944, languages: ["Bengali"] },
  { iso2: "BE", name: "Belgium", continent: "Europe", subregion: "western-europe", capital: "Brussels", lat: 50.83333333, lng: 4, capitalLat: 50.8467, capitalLng: 4.3517, languages: ["German","French","Dutch"] },
  { iso2: "BF", name: "Burkina Faso", continent: "Africa", subregion: "western-africa", capital: "Ouagadougou", lat: 13, lng: -2, capitalLat: 12.3686, capitalLng: -1.5275, languages: ["French"] },
  { iso2: "BG", name: "Bulgaria", continent: "Europe", subregion: "southeast-europe", capital: "Sofia", lat: 43, lng: 25, capitalLat: 42.6979, capitalLng: 23.3217, languages: ["Bulgarian"] },
  { iso2: "BI", name: "Burundi", continent: "Africa", subregion: "eastern-africa", capital: "Gitega", lat: -3.5, lng: 30, capitalLat: -3.4283, capitalLng: 29.925, languages: ["French","Kirundi"] },
  { iso2: "BJ", name: "Benin", continent: "Africa", subregion: "western-africa", capital: "Porto-Novo", lat: 9.5, lng: 2.25, capitalLat: 6.4833, capitalLng: 2.6167, languages: ["French"] },
  { iso2: "BN", name: "Brunei", continent: "Asia", subregion: "south-eastern-asia", capital: "Bandar Seri Begawan", lat: 4.5, lng: 114.66666666, capitalLat: 4.9167, capitalLng: 114.9167, languages: ["Malay"] },
  { iso2: "BO", name: "Bolivia", continent: "South America", subregion: "south-america", capital: "Sucre", lat: -17, lng: -65, capitalLat: -16.4958, capitalLng: -68.1333, languages: ["Aymara","Guaraní","Quechua","Spanish"] },
  { iso2: "BR", name: "Brazil", continent: "South America", subregion: "south-america", capital: "Brasília", lat: -10, lng: -55, capitalLat: -15.7939, capitalLng: -47.8828, languages: ["Portuguese"] },
  { iso2: "BS", name: "Bahamas", continent: "North America", subregion: "caribbean", capital: "Nassau", lat: 24.25, lng: -76, capitalLat: 25.0781, capitalLng: -77.3386, languages: ["English"] },
  { iso2: "BT", name: "Bhutan", continent: "Asia", subregion: "southern-asia", capital: "Thimphu", lat: 27.5, lng: 90.5, capitalLat: 27.4714, capitalLng: 89.6337, languages: ["Dzongkha"] },
  { iso2: "BW", name: "Botswana", continent: "Africa", subregion: "southern-africa", capital: "Gaborone", lat: -22, lng: 24, capitalLat: -24.6569, capitalLng: 25.9086, languages: ["English","Tswana"] },
  { iso2: "BY", name: "Belarus", continent: "Europe", subregion: "eastern-europe", capital: "Minsk", lat: 53, lng: 28, capitalLat: 53.9022, capitalLng: 27.5618, languages: ["Belarusian","Russian"] },
  { iso2: "BZ", name: "Belize", continent: "North America", subregion: "central-america", capital: "Belmopan", lat: 17.25, lng: -88.75, capitalLat: 17.25, capitalLng: -88.7675, languages: ["Belizean Creole","English","Spanish"] },
  { iso2: "CA", name: "Canada", continent: "North America", subregion: "north-america", capital: "Ottawa", lat: 60, lng: -95, capitalLat: 45.4247, capitalLng: -75.695, languages: ["English","French"] },
  { iso2: "CD", name: "Dem. Rep. Congo", continent: "Africa", subregion: "middle-africa", capital: "Kinshasa", lat: 0, lng: 25, capitalLat: -4.3219, capitalLng: 15.3119, languages: ["French","Kikongo","Lingala","Tshiluba","Swahili"] },
  { iso2: "CF", name: "Central African Rep.", continent: "Africa", subregion: "middle-africa", capital: "Bangui", lat: 7, lng: 21, capitalLat: 4.3732, capitalLng: 18.5628, languages: ["French","Sango"] },
  { iso2: "CG", name: "Congo", continent: "Africa", subregion: "middle-africa", capital: "Brazzaville", lat: -1, lng: 15, capitalLat: -4.2694, capitalLng: 15.2711, languages: ["French","Kikongo","Lingala"] },
  { iso2: "CH", name: "Switzerland", continent: "Europe", subregion: "western-europe", capital: "Bern", lat: 47, lng: 8, capitalLat: 46.948, capitalLng: 7.4474, languages: ["French","Swiss German","Italian","Romansh"] },
  { iso2: "CI", name: "Côte d'Ivoire", continent: "Africa", subregion: "western-africa", capital: "Yamoussoukro", lat: 8, lng: -5, capitalLat: 6.8161, capitalLng: -5.2742, languages: ["French"] },
  { iso2: "CL", name: "Chile", continent: "South America", subregion: "south-america", capital: "Santiago", lat: -30, lng: -71, capitalLat: -33.4375, capitalLng: -70.65, languages: ["Spanish"] },
  { iso2: "CM", name: "Cameroon", continent: "Africa", subregion: "middle-africa", capital: "Yaoundé", lat: 6, lng: 12, capitalLat: 3.8578, capitalLng: 11.5181, languages: ["English","French"] },
  { iso2: "CN", name: "China", continent: "Asia", subregion: "eastern-asia", capital: "Beijing", lat: 35, lng: 105, capitalLat: 39.904, capitalLng: 116.4075, languages: ["Chinese"] },
  { iso2: "CO", name: "Colombia", continent: "South America", subregion: "south-america", capital: "Bogotá", lat: 4, lng: -72, capitalLat: 4.6097, capitalLng: -74.0817, languages: ["Spanish"] },
  { iso2: "CR", name: "Costa Rica", continent: "North America", subregion: "central-america", capital: "San José", lat: 10, lng: -84, capitalLat: 9.9327, capitalLng: -84.0796, languages: ["Spanish"] },
  { iso2: "CU", name: "Cuba", continent: "North America", subregion: "caribbean", capital: "Havana", lat: 21.5, lng: -80, capitalLat: 23.1367, capitalLng: -82.3589, languages: ["Spanish"] },
  { iso2: "CY", name: "Cyprus", continent: "Asia", subregion: "southern-europe", capital: "Nicosia", lat: 35, lng: 33, capitalLat: 35.1725, capitalLng: 33.365, languages: ["Greek","Turkish"] },
  { iso2: "CYN", name: "N. Cyprus", continent: "Asia", subregion: "", capital: "North Nicosia", lat: 35.28, lng: 33.32, capitalLat: 35.28, capitalLng: 33.32, languages: ["Turkish"] },
  { iso2: "CZ", name: "Czechia", continent: "Europe", subregion: "central-europe", capital: "Prague", lat: 49.75, lng: 15.5, capitalLat: 50.0875, capitalLng: 14.4214, languages: ["Czech","Slovak"] },
  { iso2: "DE", name: "Germany", continent: "Europe", subregion: "western-europe", capital: "Berlin", lat: 51, lng: 9, capitalLat: 52.5167, capitalLng: 13.3833, languages: ["German"] },
  { iso2: "DJ", name: "Djibouti", continent: "Africa", subregion: "eastern-africa", capital: "Djibouti", lat: 11.5, lng: 43, capitalLat: 11.595, capitalLng: 43.1481, languages: ["Arabic","French"] },
  { iso2: "DK", name: "Denmark", continent: "Europe", subregion: "northern-europe", capital: "Copenhagen", lat: 56, lng: 10, capitalLat: 55.6761, capitalLng: 12.5689, languages: ["Danish"] },
  { iso2: "DO", name: "Dominican Rep.", continent: "North America", subregion: "caribbean", capital: "Santo Domingo", lat: 19, lng: -70.66666666, capitalLat: 18.4625, capitalLng: -69.9361, languages: ["Spanish"] },
  { iso2: "DZ", name: "Algeria", continent: "Africa", subregion: "northern-africa", capital: "Algiers", lat: 28, lng: 3, capitalLat: 36.7764, capitalLng: 3.0586, languages: ["Arabic"] },
  { iso2: "EC", name: "Ecuador", continent: "South America", subregion: "south-america", capital: "Quito", lat: -2, lng: -77.5, capitalLat: -0.22, capitalLng: -78.5125, languages: ["Spanish"] },
  { iso2: "EE", name: "Estonia", continent: "Europe", subregion: "northern-europe", capital: "Tallinn", lat: 59, lng: 26, capitalLat: 59.4372, capitalLng: 24.745, languages: ["Estonian"] },
  { iso2: "EG", name: "Egypt", continent: "Africa", subregion: "northern-africa", capital: "Cairo", lat: 27, lng: 30, capitalLat: 30.0444, capitalLng: 31.2358, languages: ["Arabic"] },
  { iso2: "EH", name: "W. Sahara", continent: "Africa", subregion: "northern-africa", capital: "El Aaiún", lat: 24.5, lng: -13, capitalLat: 24.5, capitalLng: -13, languages: ["Berber","Hassaniya","Spanish"] },
  { iso2: "ER", name: "Eritrea", continent: "Africa", subregion: "eastern-africa", capital: "Asmara", lat: 15, lng: 39, capitalLat: 15.3333, capitalLng: 38.9167, languages: ["Arabic","English","Tigrinya"] },
  { iso2: "ES", name: "Spain", continent: "Europe", subregion: "southern-europe", capital: "Madrid", lat: 40, lng: -4, capitalLat: 40.4169, capitalLng: -3.7033, languages: ["Spanish"] },
  { iso2: "ET", name: "Ethiopia", continent: "Africa", subregion: "eastern-africa", capital: "Addis Ababa", lat: 8, lng: 38, capitalLat: 9.0358, capitalLng: 38.7525, languages: ["Amharic"] },
  { iso2: "FI", name: "Finland", continent: "Europe", subregion: "northern-europe", capital: "Helsinki", lat: 64, lng: 26, capitalLat: 60.1708, capitalLng: 24.9375, languages: ["Finnish","Swedish"] },
  { iso2: "FJ", name: "Fiji", continent: "Oceania", subregion: "melanesia", capital: "Suva", lat: -18, lng: 175, capitalLat: -18.1333, capitalLng: 178.4333, languages: ["English","Fijian","Fiji Hindi"] },
  { iso2: "FK", name: "Falkland Is.", continent: "South America", subregion: "south-america", capital: "Stanley", lat: -51.75, lng: -59, capitalLat: -51.6939, capitalLng: -57.8496, languages: ["English"] },
  { iso2: "FR", name: "France", continent: "Europe", subregion: "western-europe", capital: "Paris", lat: 46, lng: 2, capitalLat: 48.8567, capitalLng: 2.3522, languages: ["French"] },
  { iso2: "GA", name: "Gabon", continent: "Africa", subregion: "middle-africa", capital: "Libreville", lat: -1, lng: 11.75, capitalLat: 0.4078, capitalLng: 9.4403, languages: ["French"] },
  { iso2: "GB", name: "United Kingdom", continent: "Europe", subregion: "northern-europe", capital: "London", lat: 54, lng: -2, capitalLat: 51.5072, capitalLng: -0.1275, languages: ["English"] },
  { iso2: "GE", name: "Georgia", continent: "Asia", subregion: "western-asia", capital: "Tbilisi", lat: 42, lng: 43.5, capitalLat: 41.7225, capitalLng: 44.7925, languages: ["Georgian"] },
  { iso2: "GH", name: "Ghana", continent: "Africa", subregion: "western-africa", capital: "Accra", lat: 8, lng: -2, capitalLat: 5.556, capitalLng: -0.1969, languages: ["English"] },
  { iso2: "GL", name: "Greenland", continent: "North America", subregion: "north-america", capital: "Nuuk", lat: 72, lng: -40, capitalLat: 64.175, capitalLng: -51.7333, languages: ["Greenlandic"] },
  { iso2: "GM", name: "Gambia", continent: "Africa", subregion: "western-africa", capital: "Banjul", lat: 13.46666666, lng: -16.56666666, capitalLat: 13.4531, capitalLng: -16.5775, languages: ["English"] },
  { iso2: "GN", name: "Guinea", continent: "Africa", subregion: "western-africa", capital: "Conakry", lat: 11, lng: -10, capitalLat: 9.5092, capitalLng: -13.7122, languages: ["French"] },
  { iso2: "GQ", name: "Eq. Guinea", continent: "Africa", subregion: "middle-africa", capital: "Malabo", lat: 2, lng: 10, capitalLat: 1.5917, capitalLng: 10.8222, languages: ["French","Portuguese","Spanish"] },
  { iso2: "GR", name: "Greece", continent: "Europe", subregion: "southern-europe", capital: "Athens", lat: 39, lng: 22, capitalLat: 37.9842, capitalLng: 23.7281, languages: ["Greek"] },
  { iso2: "GT", name: "Guatemala", continent: "North America", subregion: "central-america", capital: "Guatemala City", lat: 15.5, lng: -90.25, capitalLat: 14.6417, capitalLng: -90.5133, languages: ["Spanish"] },
  { iso2: "GW", name: "Guinea-Bissau", continent: "Africa", subregion: "western-africa", capital: "Bissau", lat: 12, lng: -15, capitalLat: 11.86, capitalLng: -15.5833, languages: ["Portuguese","Upper Guinea Creole"] },
  { iso2: "GY", name: "Guyana", continent: "South America", subregion: "south-america", capital: "Georgetown", lat: 5, lng: -59, capitalLat: 6.8058, capitalLng: -58.1508, languages: ["English"] },
  { iso2: "HN", name: "Honduras", continent: "North America", subregion: "central-america", capital: "Tegucigalpa", lat: 15, lng: -86.5, capitalLat: 14.1058, capitalLng: -87.2047, languages: ["Spanish"] },
  { iso2: "HR", name: "Croatia", continent: "Europe", subregion: "southeast-europe", capital: "Zagreb", lat: 45.16666666, lng: 15.5, capitalLat: 45.8131, capitalLng: 15.9772, languages: ["Croatian"] },
  { iso2: "HT", name: "Haiti", continent: "North America", subregion: "caribbean", capital: "Port-au-Prince", lat: 19, lng: -72.41666666, capitalLat: 18.5469, capitalLng: -72.3403, languages: ["French","Haitian Creole"] },
  { iso2: "HU", name: "Hungary", continent: "Europe", subregion: "central-europe", capital: "Budapest", lat: 47, lng: 20, capitalLat: 47.4983, capitalLng: 19.0408, languages: ["Hungarian"] },
  { iso2: "ID", name: "Indonesia", continent: "Asia", subregion: "south-eastern-asia", capital: "Jakarta", lat: -5, lng: 120, capitalLat: -6.1753, capitalLng: 106.8269, languages: ["Indonesian"] },
  { iso2: "IE", name: "Ireland", continent: "Europe", subregion: "northern-europe", capital: "Dublin", lat: 53, lng: -8, capitalLat: 53.3497, capitalLng: -6.2603, languages: ["English","Irish"] },
  { iso2: "IL", name: "Israel", continent: "Asia", subregion: "western-asia", capital: "Jerusalem", lat: 31.47, lng: 35.13, capitalLat: 31.7767, capitalLng: 35.2342, languages: ["Arabic","Hebrew"] },
  { iso2: "IN", name: "India", continent: "Asia", subregion: "southern-asia", capital: "New Delhi", lat: 20, lng: 77, capitalLat: 28.6139, capitalLng: 77.2089, languages: ["Hindi","Tamil","English"] },
  { iso2: "IQ", name: "Iraq", continent: "Asia", subregion: "western-asia", capital: "Baghdad", lat: 33, lng: 44, capitalLat: 33.3153, capitalLng: 44.3661, languages: ["Arabic","Aramaic","Sorani"] },
  { iso2: "IR", name: "Iran", continent: "Asia", subregion: "southern-asia", capital: "Tehran", lat: 32, lng: 53, capitalLat: 35.6889, capitalLng: 51.3897, languages: ["Persian (Farsi)"] },
  { iso2: "IS", name: "Iceland", continent: "Europe", subregion: "northern-europe", capital: "Reykjavik", lat: 65, lng: -18, capitalLat: 64.1475, capitalLng: -21.935, languages: ["Icelandic"] },
  { iso2: "IT", name: "Italy", continent: "Europe", subregion: "southern-europe", capital: "Rome", lat: 42.83333333, lng: 12.83333333, capitalLat: 41.8931, capitalLng: 12.4828, languages: ["Italian"] },
  { iso2: "JM", name: "Jamaica", continent: "North America", subregion: "caribbean", capital: "Kingston", lat: 18.25, lng: -77.5, capitalLat: 17.9714, capitalLng: -76.7931, languages: ["English","Jamaican Patois"] },
  { iso2: "JO", name: "Jordan", continent: "Asia", subregion: "western-asia", capital: "Amman", lat: 31, lng: 36, capitalLat: 31.95, capitalLng: 35.9333, languages: ["Arabic"] },
  { iso2: "JP", name: "Japan", continent: "Asia", subregion: "eastern-asia", capital: "Tokyo", lat: 36, lng: 138, capitalLat: 35.6894, capitalLng: 139.6917, languages: ["Japanese"] },
  { iso2: "KE", name: "Kenya", continent: "Africa", subregion: "eastern-africa", capital: "Nairobi", lat: 1, lng: 38, capitalLat: -1.2864, capitalLng: 36.8172, languages: ["English","Swahili"] },
  { iso2: "KG", name: "Kyrgyzstan", continent: "Asia", subregion: "central-asia", capital: "Bishkek", lat: 41, lng: 75, capitalLat: 42.8667, capitalLng: 74.5667, languages: ["Kyrgyz","Russian"] },
  { iso2: "KH", name: "Cambodia", continent: "Asia", subregion: "south-eastern-asia", capital: "Phnom Penh", lat: 13, lng: 105, capitalLat: 11.5696, capitalLng: 104.921, languages: ["Khmer"] },
  { iso2: "KP", name: "North Korea", continent: "Asia", subregion: "eastern-asia", capital: "Pyongyang", lat: 40, lng: 127, capitalLat: 39.0167, capitalLng: 125.7475, languages: ["Korean"] },
  { iso2: "KR", name: "South Korea", continent: "Asia", subregion: "eastern-asia", capital: "Seoul", lat: 37, lng: 127.5, capitalLat: 37.56, capitalLng: 126.99, languages: ["Korean"] },
  { iso2: "KW", name: "Kuwait", continent: "Asia", subregion: "western-asia", capital: "Kuwait City", lat: 29.5, lng: 45.75, capitalLat: 29.375, capitalLng: 47.98, languages: ["Arabic"] },
  { iso2: "KZ", name: "Kazakhstan", continent: "Asia", subregion: "central-asia", capital: "Astana", lat: 48, lng: 68, capitalLat: 51.1333, capitalLng: 71.4333, languages: ["Kazakh","Russian"] },
  { iso2: "LA", name: "Laos", continent: "Asia", subregion: "south-eastern-asia", capital: "Vientiane", lat: 18, lng: 105, capitalLat: 17.98, capitalLng: 102.63, languages: ["Lao"] },
  { iso2: "LB", name: "Lebanon", continent: "Asia", subregion: "western-asia", capital: "Beirut", lat: 33.83333333, lng: 35.83333333, capitalLat: 33.8869, capitalLng: 35.5131, languages: ["Arabic","French"] },
  { iso2: "LK", name: "Sri Lanka", continent: "Asia", subregion: "southern-asia", capital: "Colombo", lat: 7, lng: 81, capitalLat: 6.9267, capitalLng: 79.8606, languages: ["Sinhala","Tamil"] },
  { iso2: "LR", name: "Liberia", continent: "Africa", subregion: "western-africa", capital: "Monrovia", lat: 6.5, lng: -9.5, capitalLat: 6.3106, capitalLng: -10.8047, languages: ["English"] },
  { iso2: "LS", name: "Lesotho", continent: "Africa", subregion: "southern-africa", capital: "Maseru", lat: -29.5, lng: 28.5, capitalLat: -29.3167, capitalLng: 27.4833, languages: ["English","Sotho"] },
  { iso2: "LT", name: "Lithuania", continent: "Europe", subregion: "northern-europe", capital: "Vilnius", lat: 56, lng: 24, capitalLat: 54.6872, capitalLng: 25.28, languages: ["Lithuanian"] },
  { iso2: "LU", name: "Luxembourg", continent: "Europe", subregion: "western-europe", capital: "Luxembourg", lat: 49.75, lng: 6.16666666, capitalLat: 49.6106, capitalLng: 6.1328, languages: ["German","French","Luxembourgish"] },
  { iso2: "LV", name: "Latvia", continent: "Europe", subregion: "northern-europe", capital: "Riga", lat: 57, lng: 25, capitalLat: 56.9475, capitalLng: 24.1069, languages: ["Latvian"] },
  { iso2: "LY", name: "Libya", continent: "Africa", subregion: "northern-africa", capital: "Tripoli", lat: 25, lng: 17, capitalLat: 32.8875, capitalLng: 13.1875, languages: ["Arabic"] },
  { iso2: "MA", name: "Morocco", continent: "Africa", subregion: "northern-africa", capital: "Rabat", lat: 32, lng: -5, capitalLat: 34.0211, capitalLng: -6.8414, languages: ["Arabic","Berber"] },
  { iso2: "MD", name: "Moldova", continent: "Europe", subregion: "eastern-europe", capital: "Chișinău", lat: 47, lng: 29, capitalLat: 47.0228, capitalLng: 28.8353, languages: ["Moldavian"] },
  { iso2: "ME", name: "Montenegro", continent: "Europe", subregion: "southeast-europe", capital: "Podgorica", lat: 42.5, lng: 19.3, capitalLat: 42.4414, capitalLng: 19.2628, languages: ["Montenegrin"] },
  { iso2: "MG", name: "Madagascar", continent: "Africa", subregion: "eastern-africa", capital: "Antananarivo", lat: -20, lng: 47, capitalLat: -18.91, capitalLng: 47.525, languages: ["French","Malagasy"] },
  { iso2: "MK", name: "Macedonia", continent: "Europe", subregion: "southeast-europe", capital: "Skopje", lat: 41.83333333, lng: 22, capitalLat: 41.9961, capitalLng: 21.4317, languages: ["Macedonian"] },
  { iso2: "ML", name: "Mali", continent: "Africa", subregion: "western-africa", capital: "Bamako", lat: 17, lng: -4, capitalLat: 12.6458, capitalLng: -7.9922, languages: ["French"] },
  { iso2: "MM", name: "Myanmar", continent: "Asia", subregion: "south-eastern-asia", capital: "Naypyidaw", lat: 22, lng: 98, capitalLat: 19.7475, capitalLng: 96.115, languages: ["Burmese"] },
  { iso2: "MN", name: "Mongolia", continent: "Asia", subregion: "eastern-asia", capital: "Ulan Bator", lat: 46, lng: 105, capitalLat: 47.9214, capitalLng: 106.9055, languages: ["Mongolian"] },
  { iso2: "MR", name: "Mauritania", continent: "Africa", subregion: "western-africa", capital: "Nouakchott", lat: 20, lng: -12, capitalLat: 18.0858, capitalLng: -15.9785, languages: ["Arabic"] },
  { iso2: "MW", name: "Malawi", continent: "Africa", subregion: "eastern-africa", capital: "Lilongwe", lat: -13.5, lng: 34, capitalLat: -13.9864, capitalLng: 33.7681, languages: ["English","Chewa"] },
  { iso2: "MX", name: "Mexico", continent: "North America", subregion: "north-america", capital: "Mexico City", lat: 23, lng: -102, capitalLat: 19.3538, capitalLng: -99.1359, languages: ["Spanish"] },
  { iso2: "MY", name: "Malaysia", continent: "Asia", subregion: "south-eastern-asia", capital: "Kuala Lumpur", lat: 2.5, lng: 112.5, capitalLat: 3.1478, capitalLng: 101.6953, languages: ["English","Malay"] },
  { iso2: "MZ", name: "Mozambique", continent: "Africa", subregion: "eastern-africa", capital: "Maputo", lat: -18.25, lng: 35, capitalLat: -25.9689, capitalLng: 32.5733, languages: ["Portuguese"] },
  { iso2: "NA", name: "Namibia", continent: "Africa", subregion: "southern-africa", capital: "Windhoek", lat: -22, lng: 17, capitalLat: -22.57, capitalLng: 17.0836, languages: ["Afrikaans","German","English","Herero","Khoekhoe","Kwangali","Lozi","Ndonga","Tswana"] },
  { iso2: "NC", name: "New Caledonia", continent: "Oceania", subregion: "melanesia", capital: "Nouméa", lat: -21.5, lng: 165.5, capitalLat: -22.2667, capitalLng: 166.45, languages: ["French"] },
  { iso2: "NE", name: "Niger", continent: "Africa", subregion: "western-africa", capital: "Niamey", lat: 16, lng: 8, capitalLat: 13.515, capitalLng: 2.1175, languages: ["French"] },
  { iso2: "NG", name: "Nigeria", continent: "Africa", subregion: "western-africa", capital: "Abuja", lat: 10, lng: 8, capitalLat: 9.0556, capitalLng: 7.4914, languages: ["English"] },
  { iso2: "NI", name: "Nicaragua", continent: "North America", subregion: "central-america", capital: "Managua", lat: 13, lng: -85, capitalLat: 12.1547, capitalLng: -86.2737, languages: ["Spanish"] },
  { iso2: "NL", name: "Netherlands", continent: "Europe", subregion: "western-europe", capital: "Amsterdam", lat: 52.5, lng: 5.75, capitalLat: 52.3667, capitalLng: 4.8833, languages: ["Dutch"] },
  { iso2: "NO", name: "Norway", continent: "Europe", subregion: "northern-europe", capital: "Oslo", lat: 62, lng: 10, capitalLat: 59.9133, capitalLng: 10.7389, languages: ["Norwegian Nynorsk","Norwegian Bokmål","Sami"] },
  { iso2: "NP", name: "Nepal", continent: "Asia", subregion: "southern-asia", capital: "Kathmandu", lat: 28, lng: 84, capitalLat: 27.71, capitalLng: 85.32, languages: ["Nepali"] },
  { iso2: "NZ", name: "New Zealand", continent: "Oceania", subregion: "australia-and-new-zealand", capital: "Wellington", lat: -41, lng: 174, capitalLat: -41.2889, capitalLng: 174.7772, languages: ["English","Māori","New Zealand Sign Language"] },
  { iso2: "OM", name: "Oman", continent: "Asia", subregion: "western-asia", capital: "Muscat", lat: 21, lng: 57, capitalLat: 23.6139, capitalLng: 58.5922, languages: ["Arabic"] },
  { iso2: "PA", name: "Panama", continent: "North America", subregion: "central-america", capital: "Panama City", lat: 9, lng: -80, capitalLat: 8.9711, capitalLng: -79.5347, languages: ["Spanish"] },
  { iso2: "PE", name: "Peru", continent: "South America", subregion: "south-america", capital: "Lima", lat: -10, lng: -76, capitalLat: -12.06, capitalLng: -77.0375, languages: ["Aymara","Quechua","Spanish"] },
  { iso2: "PG", name: "Papua New Guinea", continent: "Oceania", subregion: "melanesia", capital: "Port Moresby", lat: -6, lng: 147, capitalLat: -9.4789, capitalLng: 147.1494, languages: ["English","Hiri Motu","Tok Pisin"] },
  { iso2: "PH", name: "Philippines", continent: "Asia", subregion: "south-eastern-asia", capital: "Manila", lat: 13, lng: 122, capitalLat: 14.5958, capitalLng: 120.9772, languages: ["English","Filipino"] },
  { iso2: "PK", name: "Pakistan", continent: "Asia", subregion: "southern-asia", capital: "Islamabad", lat: 30, lng: 70, capitalLat: 33.6989, capitalLng: 73.0369, languages: ["English","Urdu"] },
  { iso2: "PL", name: "Poland", continent: "Europe", subregion: "central-europe", capital: "Warsaw", lat: 52, lng: 20, capitalLat: 52.23, capitalLng: 21.0111, languages: ["Polish"] },
  { iso2: "PR", name: "Puerto Rico", continent: "North America", subregion: "caribbean", capital: "San Juan", lat: 18.25, lng: -66.5, capitalLat: 18.4653, capitalLng: -66.1167, languages: ["English","Spanish"] },
  { iso2: "PS", name: "Palestine", continent: "Asia", subregion: "western-asia", capital: "Ramallah", lat: 31.9, lng: 35.2, capitalLat: 31.7834, capitalLng: 35.2339, languages: ["Arabic"] },
  { iso2: "PT", name: "Portugal", continent: "Europe", subregion: "southern-europe", capital: "Lisbon", lat: 39.5, lng: -8, capitalLat: 38.708, capitalLng: -9.139, languages: ["Portuguese"] },
  { iso2: "PY", name: "Paraguay", continent: "South America", subregion: "south-america", capital: "Asunción", lat: -23, lng: -58, capitalLat: -25.28, capitalLng: -57.6344, languages: ["Guaraní","Spanish"] },
  { iso2: "QA", name: "Qatar", continent: "Asia", subregion: "western-asia", capital: "Doha", lat: 25.5, lng: 51.25, capitalLat: 25.2861, capitalLng: 51.5294, languages: ["Arabic"] },
  { iso2: "RO", name: "Romania", continent: "Europe", subregion: "southeast-europe", capital: "Bucharest", lat: 46, lng: 25, capitalLat: 44.4134, capitalLng: 26.0978, languages: ["Romanian"] },
  { iso2: "RS", name: "Serbia", continent: "Europe", subregion: "southeast-europe", capital: "Belgrade", lat: 44, lng: 21, capitalLat: 44.8178, capitalLng: 20.4569, languages: ["Serbian"] },
  { iso2: "RU", name: "Russia", continent: "Europe", subregion: "eastern-europe", capital: "Moscow", lat: 60, lng: 100, capitalLat: 55.7506, capitalLng: 37.6175, languages: ["Russian"] },
  { iso2: "RW", name: "Rwanda", continent: "Africa", subregion: "eastern-africa", capital: "Kigali", lat: -2, lng: 30, capitalLat: -1.9525, capitalLng: 30.115, languages: ["English","French","Kinyarwanda"] },
  { iso2: "SA", name: "Saudi Arabia", continent: "Asia", subregion: "western-asia", capital: "Riyadh", lat: 25, lng: 45, capitalLat: 24.65, capitalLng: 46.71, languages: ["Arabic"] },
  { iso2: "SB", name: "Solomon Is.", continent: "Oceania", subregion: "melanesia", capital: "Honiara", lat: -8, lng: 159, capitalLat: -9.4333, capitalLng: 159.95, languages: ["English"] },
  { iso2: "SD", name: "Sudan", continent: "Africa", subregion: "northern-africa", capital: "Khartoum", lat: 15, lng: 30, capitalLat: 15.6031, capitalLng: 32.5265, languages: ["Arabic","English"] },
  { iso2: "SE", name: "Sweden", continent: "Europe", subregion: "northern-europe", capital: "Stockholm", lat: 62, lng: 15, capitalLat: 59.3294, capitalLng: 18.0686, languages: ["Swedish"] },
  { iso2: "SI", name: "Slovenia", continent: "Europe", subregion: "central-europe", capital: "Ljubljana", lat: 46.11666666, lng: 14.81666666, capitalLat: 46.0514, capitalLng: 14.5061, languages: ["Slovene"] },
  { iso2: "SK", name: "Slovakia", continent: "Europe", subregion: "central-europe", capital: "Bratislava", lat: 48.66666666, lng: 19.5, capitalLat: 48.1482, capitalLng: 17.1067, languages: ["Slovak"] },
  { iso2: "SL", name: "Sierra Leone", continent: "Africa", subregion: "western-africa", capital: "Freetown", lat: 8.5, lng: -11.5, capitalLat: 8.4872, capitalLng: -13.2356, languages: ["English"] },
  { iso2: "SN", name: "Senegal", continent: "Africa", subregion: "western-africa", capital: "Dakar", lat: 14, lng: -14, capitalLat: 14.6726, capitalLng: -17.432, languages: ["French"] },
  { iso2: "SO", name: "Somalia", continent: "Africa", subregion: "eastern-africa", capital: "Mogadishu", lat: 10, lng: 49, capitalLat: 2.0392, capitalLng: 45.3419, languages: ["Arabic","Somali"] },
  { iso2: "SOL", name: "Somaliland", continent: "Africa", subregion: "", capital: "Hargeisa", lat: 9.55, lng: 44.05, capitalLat: 9.55, capitalLng: 44.05, languages: ["Somali","Arabic"] },
  { iso2: "SR", name: "Suriname", continent: "South America", subregion: "south-america", capital: "Paramaribo", lat: 4, lng: -56, capitalLat: 5.8667, capitalLng: -55.1667, languages: ["Dutch"] },
  { iso2: "SS", name: "S. Sudan", continent: "Africa", subregion: "middle-africa", capital: "Juba", lat: 7, lng: 30, capitalLat: 4.8539, capitalLng: 31.5825, languages: ["English"] },
  { iso2: "SV", name: "El Salvador", continent: "North America", subregion: "central-america", capital: "San Salvador", lat: 13.83333333, lng: -88.91666666, capitalLat: 13.6976, capitalLng: -89.1912, languages: ["Spanish"] },
  { iso2: "SY", name: "Syria", continent: "Asia", subregion: "western-asia", capital: "Damascus", lat: 35, lng: 38, capitalLat: 33.5131, capitalLng: 36.2919, languages: ["Arabic"] },
  { iso2: "SZ", name: "Swaziland", continent: "Africa", subregion: "southern-africa", capital: "Lobamba", lat: -26.5, lng: 31.5, capitalLat: -26.3167, capitalLng: 31.1333, languages: ["English","Swazi"] },
  { iso2: "TD", name: "Chad", continent: "Africa", subregion: "middle-africa", capital: "N'Djamena", lat: 15, lng: 19, capitalLat: 12.11, capitalLng: 15.05, languages: ["Arabic","French"] },
  { iso2: "TF", name: "Fr. S. Antarctic Lands", continent: "Seven seas (open ocean)", subregion: "", capital: "Port-aux-Français", lat: -49.25, lng: 69.167, capitalLat: -49.35, capitalLng: 70.2167, languages: ["French"] },
  { iso2: "TG", name: "Togo", continent: "Africa", subregion: "western-africa", capital: "Lomé", lat: 8, lng: 1.16666666, capitalLat: 6.13, capitalLng: 1.2158, languages: ["French"] },
  { iso2: "TH", name: "Thailand", continent: "Asia", subregion: "south-eastern-asia", capital: "Bangkok", lat: 15, lng: 100, capitalLat: 13.75, capitalLng: 100.5167, languages: ["Thai"] },
  { iso2: "TJ", name: "Tajikistan", continent: "Asia", subregion: "central-asia", capital: "Dushanbe", lat: 39, lng: 71, capitalLat: 38.5731, capitalLng: 68.7864, languages: ["Russian","Tajik"] },
  { iso2: "TL", name: "Timor-Leste", continent: "Asia", subregion: "south-eastern-asia", capital: "Dili", lat: -8.83333333, lng: 125.91666666, capitalLat: -8.5536, capitalLng: 125.5783, languages: ["Portuguese","Tetum"] },
  { iso2: "TM", name: "Turkmenistan", continent: "Asia", subregion: "central-asia", capital: "Ashgabat", lat: 40, lng: 60, capitalLat: 37.95, capitalLng: 58.3833, languages: ["Russian","Turkmen"] },
  { iso2: "TN", name: "Tunisia", continent: "Africa", subregion: "northern-africa", capital: "Tunis", lat: 34, lng: 9, capitalLat: 36.8008, capitalLng: 10.18, languages: ["Arabic"] },
  { iso2: "TR", name: "Turkey", continent: "Asia", subregion: "western-asia", capital: "Ankara", lat: 39, lng: 35, capitalLat: 39.9358, capitalLng: 32.8387, languages: ["Turkish"] },
  { iso2: "TT", name: "Trinidad and Tobago", continent: "North America", subregion: "caribbean", capital: "Port of Spain", lat: 11, lng: -61, capitalLat: 10.6667, capitalLng: -61.5167, languages: ["English"] },
  { iso2: "TW", name: "Taiwan", continent: "Asia", subregion: "eastern-asia", capital: "Taipei", lat: 23.5, lng: 121, capitalLat: 25.0375, capitalLng: 121.5625, languages: ["Chinese"] },
  { iso2: "TZ", name: "Tanzania", continent: "Africa", subregion: "eastern-africa", capital: "Dodoma", lat: -6, lng: 35, capitalLat: -6.1835, capitalLng: 35.746, languages: ["English","Swahili"] },
  { iso2: "UA", name: "Ukraine", continent: "Europe", subregion: "eastern-europe", capital: "Kyiv", lat: 49, lng: 32, capitalLat: 50.45, capitalLng: 30.5236, languages: ["Ukrainian"] },
  { iso2: "UG", name: "Uganda", continent: "Africa", subregion: "eastern-africa", capital: "Kampala", lat: 1, lng: 32, capitalLat: 0.3136, capitalLng: 32.5811, languages: ["English","Swahili"] },
  { iso2: "US", name: "United States of America", continent: "North America", subregion: "north-america", capital: "Washington D.C.", lat: 38, lng: -97, capitalLat: 38.895, capitalLng: -77.0367, languages: ["English"] },
  { iso2: "UY", name: "Uruguay", continent: "South America", subregion: "south-america", capital: "Montevideo", lat: -33, lng: -56, capitalLat: -34.9059, capitalLng: -56.1913, languages: ["Spanish"] },
  { iso2: "UZ", name: "Uzbekistan", continent: "Asia", subregion: "central-asia", capital: "Tashkent", lat: 41, lng: 64, capitalLat: 41.3111, capitalLng: 69.2797, languages: ["Russian","Uzbek"] },
  { iso2: "VE", name: "Venezuela", continent: "South America", subregion: "south-america", capital: "Caracas", lat: 8, lng: -66, capitalLat: 10.5061, capitalLng: -66.9144, languages: ["Spanish"] },
  { iso2: "VN", name: "Vietnam", continent: "Asia", subregion: "south-eastern-asia", capital: "Hanoi", lat: 16.16666666, lng: 107.83333333, capitalLat: 21.0245, capitalLng: 105.8412, languages: ["Vietnamese"] },
  { iso2: "VU", name: "Vanuatu", continent: "Oceania", subregion: "melanesia", capital: "Port Vila", lat: -16, lng: 167, capitalLat: -17.7333, capitalLng: 168.3167, languages: ["Bislama","English","French"] },
  { iso2: "XK", name: "Kosovo", continent: "Europe", subregion: "southeast-europe", capital: "Pristina", lat: 42.666667, lng: 21.166667, capitalLat: 42.6667, capitalLng: 21.1667, languages: ["Albanian","Serbian"] },
  { iso2: "YE", name: "Yemen", continent: "Asia", subregion: "western-asia", capital: "Sana'a", lat: 15, lng: 48, capitalLat: 12.8, capitalLng: 45.0333, languages: ["Arabic"] },
  { iso2: "ZA", name: "South Africa", continent: "Africa", subregion: "southern-africa", capital: "Pretoria", lat: -29, lng: 24, capitalLat: -25.7464, capitalLng: 28.1881, languages: ["Afrikaans","English","Southern Ndebele","Northern Sotho","Southern Sotho","Swazi","Tswana","Tsonga","Venda","Xhosa","Zulu"] },
  { iso2: "ZM", name: "Zambia", continent: "Africa", subregion: "eastern-africa", capital: "Lusaka", lat: -15, lng: 30, capitalLat: -15.4167, capitalLng: 28.2833, languages: ["English"] },
  { iso2: "ZW", name: "Zimbabwe", continent: "Africa", subregion: "eastern-africa", capital: "Harare", lat: -20, lng: 30, capitalLat: -17.8292, capitalLng: 31.0522, languages: ["Chibarwe","English","Kalanga","Khoisan","Ndau","Northern Ndebele","Chewa","Shona","Sotho","Tonga","Tswana","Tsonga","Venda","Xhosa","Zimbabwean Sign Language"] },
];

const byIso2 = new Map(COUNTRY_INDEX.map((c) => [c.iso2, c]));

export function findCountry(iso2: string): CountryInfo | null {
  return byIso2.get(iso2.toUpperCase()) ?? null;
}
