// Country properties without geometry, generated from
// public/data/countries-enriched.geojson.
//
// Lets pages that only need names, capitals, and coordinates avoid pulling in
// the full 1.4MB geojson (which exists for the globe's polygons).

export type CountryInfo = {
  iso2: string;
  name: string;
  continent: string;
  capital: string;
  lat: number;
  lng: number;
  languages: string[];
};

export const COUNTRY_INDEX: CountryInfo[] = [
  { iso2: "AE", name: "United Arab Emirates", continent: "Asia", capital: "Abu Dhabi", lat: 24, lng: 54, languages: ["Arabic"] },
  { iso2: "AF", name: "Afghanistan", continent: "Asia", capital: "Kabul", lat: 33, lng: 65, languages: ["Dari","Pashto","Turkmen"] },
  { iso2: "AL", name: "Albania", continent: "Europe", capital: "Tirana", lat: 41, lng: 20, languages: ["Albanian"] },
  { iso2: "AM", name: "Armenia", continent: "Asia", capital: "Yerevan", lat: 40, lng: 45, languages: ["Armenian"] },
  { iso2: "AO", name: "Angola", continent: "Africa", capital: "Luanda", lat: -12.5, lng: 18.5, languages: ["Portuguese"] },
  { iso2: "AQ", name: "Antarctica", continent: "Antarctica", capital: "Antarctica", lat: -90, lng: 0, languages: [] },
  { iso2: "AR", name: "Argentina", continent: "South America", capital: "Buenos Aires", lat: -34, lng: -64, languages: ["Guaraní","Spanish"] },
  { iso2: "AT", name: "Austria", continent: "Europe", capital: "Vienna", lat: 47.33333333, lng: 13.33333333, languages: ["Austro-Bavarian German"] },
  { iso2: "AU", name: "Australia", continent: "Oceania", capital: "Canberra", lat: -27, lng: 133, languages: ["English"] },
  { iso2: "AZ", name: "Azerbaijan", continent: "Asia", capital: "Baku", lat: 40.5, lng: 47.5, languages: ["Azerbaijani","Russian"] },
  { iso2: "BA", name: "Bosnia and Herz.", continent: "Europe", capital: "Sarajevo", lat: 44, lng: 18, languages: ["Bosnian","Croatian","Serbian"] },
  { iso2: "BD", name: "Bangladesh", continent: "Asia", capital: "Dhaka", lat: 24, lng: 90, languages: ["Bengali"] },
  { iso2: "BE", name: "Belgium", continent: "Europe", capital: "Brussels", lat: 50.83333333, lng: 4, languages: ["German","French","Dutch"] },
  { iso2: "BF", name: "Burkina Faso", continent: "Africa", capital: "Ouagadougou", lat: 13, lng: -2, languages: ["French"] },
  { iso2: "BG", name: "Bulgaria", continent: "Europe", capital: "Sofia", lat: 43, lng: 25, languages: ["Bulgarian"] },
  { iso2: "BI", name: "Burundi", continent: "Africa", capital: "Gitega", lat: -3.5, lng: 30, languages: ["French","Kirundi"] },
  { iso2: "BJ", name: "Benin", continent: "Africa", capital: "Porto-Novo", lat: 9.5, lng: 2.25, languages: ["French"] },
  { iso2: "BN", name: "Brunei", continent: "Asia", capital: "Bandar Seri Begawan", lat: 4.5, lng: 114.66666666, languages: ["Malay"] },
  { iso2: "BO", name: "Bolivia", continent: "South America", capital: "Sucre", lat: -17, lng: -65, languages: ["Aymara","Guaraní","Quechua","Spanish"] },
  { iso2: "BR", name: "Brazil", continent: "South America", capital: "Brasília", lat: -10, lng: -55, languages: ["Portuguese"] },
  { iso2: "BS", name: "Bahamas", continent: "North America", capital: "Nassau", lat: 24.25, lng: -76, languages: ["English"] },
  { iso2: "BT", name: "Bhutan", continent: "Asia", capital: "Thimphu", lat: 27.5, lng: 90.5, languages: ["Dzongkha"] },
  { iso2: "BW", name: "Botswana", continent: "Africa", capital: "Gaborone", lat: -22, lng: 24, languages: ["English","Tswana"] },
  { iso2: "BY", name: "Belarus", continent: "Europe", capital: "Minsk", lat: 53, lng: 28, languages: ["Belarusian","Russian"] },
  { iso2: "BZ", name: "Belize", continent: "North America", capital: "Belmopan", lat: 17.25, lng: -88.75, languages: ["Belizean Creole","English","Spanish"] },
  { iso2: "CA", name: "Canada", continent: "North America", capital: "Ottawa", lat: 60, lng: -95, languages: ["English","French"] },
  { iso2: "CD", name: "Dem. Rep. Congo", continent: "Africa", capital: "Kinshasa", lat: 0, lng: 25, languages: ["French","Kikongo","Lingala","Tshiluba","Swahili"] },
  { iso2: "CF", name: "Central African Rep.", continent: "Africa", capital: "Bangui", lat: 7, lng: 21, languages: ["French","Sango"] },
  { iso2: "CG", name: "Congo", continent: "Africa", capital: "Brazzaville", lat: -1, lng: 15, languages: ["French","Kikongo","Lingala"] },
  { iso2: "CH", name: "Switzerland", continent: "Europe", capital: "Bern", lat: 47, lng: 8, languages: ["French","Swiss German","Italian","Romansh"] },
  { iso2: "CI", name: "Côte d'Ivoire", continent: "Africa", capital: "Yamoussoukro", lat: 8, lng: -5, languages: ["French"] },
  { iso2: "CL", name: "Chile", continent: "South America", capital: "Santiago", lat: -30, lng: -71, languages: ["Spanish"] },
  { iso2: "CM", name: "Cameroon", continent: "Africa", capital: "Yaoundé", lat: 6, lng: 12, languages: ["English","French"] },
  { iso2: "CN", name: "China", continent: "Asia", capital: "Beijing", lat: 35, lng: 105, languages: ["Chinese"] },
  { iso2: "CO", name: "Colombia", continent: "South America", capital: "Bogotá", lat: 4, lng: -72, languages: ["Spanish"] },
  { iso2: "CR", name: "Costa Rica", continent: "North America", capital: "San José", lat: 10, lng: -84, languages: ["Spanish"] },
  { iso2: "CU", name: "Cuba", continent: "North America", capital: "Havana", lat: 21.5, lng: -80, languages: ["Spanish"] },
  { iso2: "CY", name: "Cyprus", continent: "Asia", capital: "Nicosia", lat: 35, lng: 33, languages: ["Greek","Turkish"] },
  { iso2: "CYN", name: "N. Cyprus", continent: "Asia", capital: "North Nicosia", lat: 35.28, lng: 33.32, languages: ["Turkish"] },
  { iso2: "CZ", name: "Czechia", continent: "Europe", capital: "Prague", lat: 49.75, lng: 15.5, languages: ["Czech","Slovak"] },
  { iso2: "DE", name: "Germany", continent: "Europe", capital: "Berlin", lat: 51, lng: 9, languages: ["German"] },
  { iso2: "DJ", name: "Djibouti", continent: "Africa", capital: "Djibouti", lat: 11.5, lng: 43, languages: ["Arabic","French"] },
  { iso2: "DK", name: "Denmark", continent: "Europe", capital: "Copenhagen", lat: 56, lng: 10, languages: ["Danish"] },
  { iso2: "DO", name: "Dominican Rep.", continent: "North America", capital: "Santo Domingo", lat: 19, lng: -70.66666666, languages: ["Spanish"] },
  { iso2: "DZ", name: "Algeria", continent: "Africa", capital: "Algiers", lat: 28, lng: 3, languages: ["Arabic"] },
  { iso2: "EC", name: "Ecuador", continent: "South America", capital: "Quito", lat: -2, lng: -77.5, languages: ["Spanish"] },
  { iso2: "EE", name: "Estonia", continent: "Europe", capital: "Tallinn", lat: 59, lng: 26, languages: ["Estonian"] },
  { iso2: "EG", name: "Egypt", continent: "Africa", capital: "Cairo", lat: 27, lng: 30, languages: ["Arabic"] },
  { iso2: "EH", name: "W. Sahara", continent: "Africa", capital: "El Aaiún", lat: 24.5, lng: -13, languages: ["Berber","Hassaniya","Spanish"] },
  { iso2: "ER", name: "Eritrea", continent: "Africa", capital: "Asmara", lat: 15, lng: 39, languages: ["Arabic","English","Tigrinya"] },
  { iso2: "ES", name: "Spain", continent: "Europe", capital: "Madrid", lat: 40, lng: -4, languages: ["Spanish"] },
  { iso2: "ET", name: "Ethiopia", continent: "Africa", capital: "Addis Ababa", lat: 8, lng: 38, languages: ["Amharic"] },
  { iso2: "FI", name: "Finland", continent: "Europe", capital: "Helsinki", lat: 64, lng: 26, languages: ["Finnish","Swedish"] },
  { iso2: "FJ", name: "Fiji", continent: "Oceania", capital: "Suva", lat: -18, lng: 175, languages: ["English","Fijian","Fiji Hindi"] },
  { iso2: "FK", name: "Falkland Is.", continent: "South America", capital: "Stanley", lat: -51.75, lng: -59, languages: ["English"] },
  { iso2: "FR", name: "France", continent: "Europe", capital: "Paris", lat: 46, lng: 2, languages: ["French"] },
  { iso2: "GA", name: "Gabon", continent: "Africa", capital: "Libreville", lat: -1, lng: 11.75, languages: ["French"] },
  { iso2: "GB", name: "United Kingdom", continent: "Europe", capital: "London", lat: 54, lng: -2, languages: ["English"] },
  { iso2: "GE", name: "Georgia", continent: "Asia", capital: "Tbilisi", lat: 42, lng: 43.5, languages: ["Georgian"] },
  { iso2: "GH", name: "Ghana", continent: "Africa", capital: "Accra", lat: 8, lng: -2, languages: ["English"] },
  { iso2: "GL", name: "Greenland", continent: "North America", capital: "Nuuk", lat: 72, lng: -40, languages: ["Greenlandic"] },
  { iso2: "GM", name: "Gambia", continent: "Africa", capital: "Banjul", lat: 13.46666666, lng: -16.56666666, languages: ["English"] },
  { iso2: "GN", name: "Guinea", continent: "Africa", capital: "Conakry", lat: 11, lng: -10, languages: ["French"] },
  { iso2: "GQ", name: "Eq. Guinea", continent: "Africa", capital: "Malabo", lat: 2, lng: 10, languages: ["French","Portuguese","Spanish"] },
  { iso2: "GR", name: "Greece", continent: "Europe", capital: "Athens", lat: 39, lng: 22, languages: ["Greek"] },
  { iso2: "GT", name: "Guatemala", continent: "North America", capital: "Guatemala City", lat: 15.5, lng: -90.25, languages: ["Spanish"] },
  { iso2: "GW", name: "Guinea-Bissau", continent: "Africa", capital: "Bissau", lat: 12, lng: -15, languages: ["Portuguese","Upper Guinea Creole"] },
  { iso2: "GY", name: "Guyana", continent: "South America", capital: "Georgetown", lat: 5, lng: -59, languages: ["English"] },
  { iso2: "HN", name: "Honduras", continent: "North America", capital: "Tegucigalpa", lat: 15, lng: -86.5, languages: ["Spanish"] },
  { iso2: "HR", name: "Croatia", continent: "Europe", capital: "Zagreb", lat: 45.16666666, lng: 15.5, languages: ["Croatian"] },
  { iso2: "HT", name: "Haiti", continent: "North America", capital: "Port-au-Prince", lat: 19, lng: -72.41666666, languages: ["French","Haitian Creole"] },
  { iso2: "HU", name: "Hungary", continent: "Europe", capital: "Budapest", lat: 47, lng: 20, languages: ["Hungarian"] },
  { iso2: "ID", name: "Indonesia", continent: "Asia", capital: "Jakarta", lat: -5, lng: 120, languages: ["Indonesian"] },
  { iso2: "IE", name: "Ireland", continent: "Europe", capital: "Dublin", lat: 53, lng: -8, languages: ["English","Irish"] },
  { iso2: "IL", name: "Israel", continent: "Asia", capital: "Jerusalem", lat: 31.47, lng: 35.13, languages: ["Arabic","Hebrew"] },
  { iso2: "IN", name: "India", continent: "Asia", capital: "New Delhi", lat: 20, lng: 77, languages: ["English","Hindi","Tamil"] },
  { iso2: "IQ", name: "Iraq", continent: "Asia", capital: "Baghdad", lat: 33, lng: 44, languages: ["Arabic","Aramaic","Sorani"] },
  { iso2: "IR", name: "Iran", continent: "Asia", capital: "Tehran", lat: 32, lng: 53, languages: ["Persian (Farsi)"] },
  { iso2: "IS", name: "Iceland", continent: "Europe", capital: "Reykjavik", lat: 65, lng: -18, languages: ["Icelandic"] },
  { iso2: "IT", name: "Italy", continent: "Europe", capital: "Rome", lat: 42.83333333, lng: 12.83333333, languages: ["Italian"] },
  { iso2: "JM", name: "Jamaica", continent: "North America", capital: "Kingston", lat: 18.25, lng: -77.5, languages: ["English","Jamaican Patois"] },
  { iso2: "JO", name: "Jordan", continent: "Asia", capital: "Amman", lat: 31, lng: 36, languages: ["Arabic"] },
  { iso2: "JP", name: "Japan", continent: "Asia", capital: "Tokyo", lat: 36, lng: 138, languages: ["Japanese"] },
  { iso2: "KE", name: "Kenya", continent: "Africa", capital: "Nairobi", lat: 1, lng: 38, languages: ["English","Swahili"] },
  { iso2: "KG", name: "Kyrgyzstan", continent: "Asia", capital: "Bishkek", lat: 41, lng: 75, languages: ["Kyrgyz","Russian"] },
  { iso2: "KH", name: "Cambodia", continent: "Asia", capital: "Phnom Penh", lat: 13, lng: 105, languages: ["Khmer"] },
  { iso2: "KP", name: "North Korea", continent: "Asia", capital: "Pyongyang", lat: 40, lng: 127, languages: ["Korean"] },
  { iso2: "KR", name: "South Korea", continent: "Asia", capital: "Seoul", lat: 37, lng: 127.5, languages: ["Korean"] },
  { iso2: "KW", name: "Kuwait", continent: "Asia", capital: "Kuwait City", lat: 29.5, lng: 45.75, languages: ["Arabic"] },
  { iso2: "KZ", name: "Kazakhstan", continent: "Asia", capital: "Astana", lat: 48, lng: 68, languages: ["Kazakh","Russian"] },
  { iso2: "LA", name: "Laos", continent: "Asia", capital: "Vientiane", lat: 18, lng: 105, languages: ["Lao"] },
  { iso2: "LB", name: "Lebanon", continent: "Asia", capital: "Beirut", lat: 33.83333333, lng: 35.83333333, languages: ["Arabic","French"] },
  { iso2: "LK", name: "Sri Lanka", continent: "Asia", capital: "Colombo", lat: 7, lng: 81, languages: ["Sinhala","Tamil"] },
  { iso2: "LR", name: "Liberia", continent: "Africa", capital: "Monrovia", lat: 6.5, lng: -9.5, languages: ["English"] },
  { iso2: "LS", name: "Lesotho", continent: "Africa", capital: "Maseru", lat: -29.5, lng: 28.5, languages: ["English","Sotho"] },
  { iso2: "LT", name: "Lithuania", continent: "Europe", capital: "Vilnius", lat: 56, lng: 24, languages: ["Lithuanian"] },
  { iso2: "LU", name: "Luxembourg", continent: "Europe", capital: "Luxembourg", lat: 49.75, lng: 6.16666666, languages: ["German","French","Luxembourgish"] },
  { iso2: "LV", name: "Latvia", continent: "Europe", capital: "Riga", lat: 57, lng: 25, languages: ["Latvian"] },
  { iso2: "LY", name: "Libya", continent: "Africa", capital: "Tripoli", lat: 25, lng: 17, languages: ["Arabic"] },
  { iso2: "MA", name: "Morocco", continent: "Africa", capital: "Rabat", lat: 32, lng: -5, languages: ["Arabic","Berber"] },
  { iso2: "MD", name: "Moldova", continent: "Europe", capital: "Chișinău", lat: 47, lng: 29, languages: ["Moldavian"] },
  { iso2: "ME", name: "Montenegro", continent: "Europe", capital: "Podgorica", lat: 42.5, lng: 19.3, languages: ["Montenegrin"] },
  { iso2: "MG", name: "Madagascar", continent: "Africa", capital: "Antananarivo", lat: -20, lng: 47, languages: ["French","Malagasy"] },
  { iso2: "MK", name: "Macedonia", continent: "Europe", capital: "Skopje", lat: 41.83333333, lng: 22, languages: ["Macedonian"] },
  { iso2: "ML", name: "Mali", continent: "Africa", capital: "Bamako", lat: 17, lng: -4, languages: ["French"] },
  { iso2: "MM", name: "Myanmar", continent: "Asia", capital: "Naypyidaw", lat: 22, lng: 98, languages: ["Burmese"] },
  { iso2: "MN", name: "Mongolia", continent: "Asia", capital: "Ulan Bator", lat: 46, lng: 105, languages: ["Mongolian"] },
  { iso2: "MR", name: "Mauritania", continent: "Africa", capital: "Nouakchott", lat: 20, lng: -12, languages: ["Arabic"] },
  { iso2: "MW", name: "Malawi", continent: "Africa", capital: "Lilongwe", lat: -13.5, lng: 34, languages: ["English","Chewa"] },
  { iso2: "MX", name: "Mexico", continent: "North America", capital: "Mexico City", lat: 23, lng: -102, languages: ["Spanish"] },
  { iso2: "MY", name: "Malaysia", continent: "Asia", capital: "Kuala Lumpur", lat: 2.5, lng: 112.5, languages: ["English","Malay"] },
  { iso2: "MZ", name: "Mozambique", continent: "Africa", capital: "Maputo", lat: -18.25, lng: 35, languages: ["Portuguese"] },
  { iso2: "NA", name: "Namibia", continent: "Africa", capital: "Windhoek", lat: -22, lng: 17, languages: ["Afrikaans","German","English","Herero","Khoekhoe","Kwangali","Lozi","Ndonga","Tswana"] },
  { iso2: "NC", name: "New Caledonia", continent: "Oceania", capital: "Nouméa", lat: -21.5, lng: 165.5, languages: ["French"] },
  { iso2: "NE", name: "Niger", continent: "Africa", capital: "Niamey", lat: 16, lng: 8, languages: ["French"] },
  { iso2: "NG", name: "Nigeria", continent: "Africa", capital: "Abuja", lat: 10, lng: 8, languages: ["English"] },
  { iso2: "NI", name: "Nicaragua", continent: "North America", capital: "Managua", lat: 13, lng: -85, languages: ["Spanish"] },
  { iso2: "NL", name: "Netherlands", continent: "Europe", capital: "Amsterdam", lat: 52.5, lng: 5.75, languages: ["Dutch"] },
  { iso2: "NO", name: "Norway", continent: "Europe", capital: "Oslo", lat: 62, lng: 10, languages: ["Norwegian Nynorsk","Norwegian Bokmål","Sami"] },
  { iso2: "NP", name: "Nepal", continent: "Asia", capital: "Kathmandu", lat: 28, lng: 84, languages: ["Nepali"] },
  { iso2: "NZ", name: "New Zealand", continent: "Oceania", capital: "Wellington", lat: -41, lng: 174, languages: ["English","Māori","New Zealand Sign Language"] },
  { iso2: "OM", name: "Oman", continent: "Asia", capital: "Muscat", lat: 21, lng: 57, languages: ["Arabic"] },
  { iso2: "PA", name: "Panama", continent: "North America", capital: "Panama City", lat: 9, lng: -80, languages: ["Spanish"] },
  { iso2: "PE", name: "Peru", continent: "South America", capital: "Lima", lat: -10, lng: -76, languages: ["Aymara","Quechua","Spanish"] },
  { iso2: "PG", name: "Papua New Guinea", continent: "Oceania", capital: "Port Moresby", lat: -6, lng: 147, languages: ["English","Hiri Motu","Tok Pisin"] },
  { iso2: "PH", name: "Philippines", continent: "Asia", capital: "Manila", lat: 13, lng: 122, languages: ["English","Filipino"] },
  { iso2: "PK", name: "Pakistan", continent: "Asia", capital: "Islamabad", lat: 30, lng: 70, languages: ["English","Urdu"] },
  { iso2: "PL", name: "Poland", continent: "Europe", capital: "Warsaw", lat: 52, lng: 20, languages: ["Polish"] },
  { iso2: "PR", name: "Puerto Rico", continent: "North America", capital: "San Juan", lat: 18.25, lng: -66.5, languages: ["English","Spanish"] },
  { iso2: "PS", name: "Palestine", continent: "Asia", capital: "Ramallah", lat: 31.9, lng: 35.2, languages: ["Arabic"] },
  { iso2: "PT", name: "Portugal", continent: "Europe", capital: "Lisbon", lat: 39.5, lng: -8, languages: ["Portuguese"] },
  { iso2: "PY", name: "Paraguay", continent: "South America", capital: "Asunción", lat: -23, lng: -58, languages: ["Guaraní","Spanish"] },
  { iso2: "QA", name: "Qatar", continent: "Asia", capital: "Doha", lat: 25.5, lng: 51.25, languages: ["Arabic"] },
  { iso2: "RO", name: "Romania", continent: "Europe", capital: "Bucharest", lat: 46, lng: 25, languages: ["Romanian"] },
  { iso2: "RS", name: "Serbia", continent: "Europe", capital: "Belgrade", lat: 44, lng: 21, languages: ["Serbian"] },
  { iso2: "RU", name: "Russia", continent: "Europe", capital: "Moscow", lat: 60, lng: 100, languages: ["Russian"] },
  { iso2: "RW", name: "Rwanda", continent: "Africa", capital: "Kigali", lat: -2, lng: 30, languages: ["English","French","Kinyarwanda"] },
  { iso2: "SA", name: "Saudi Arabia", continent: "Asia", capital: "Riyadh", lat: 25, lng: 45, languages: ["Arabic"] },
  { iso2: "SB", name: "Solomon Is.", continent: "Oceania", capital: "Honiara", lat: -8, lng: 159, languages: ["English"] },
  { iso2: "SD", name: "Sudan", continent: "Africa", capital: "Khartoum", lat: 15, lng: 30, languages: ["Arabic","English"] },
  { iso2: "SE", name: "Sweden", continent: "Europe", capital: "Stockholm", lat: 62, lng: 15, languages: ["Swedish"] },
  { iso2: "SI", name: "Slovenia", continent: "Europe", capital: "Ljubljana", lat: 46.11666666, lng: 14.81666666, languages: ["Slovene"] },
  { iso2: "SK", name: "Slovakia", continent: "Europe", capital: "Bratislava", lat: 48.66666666, lng: 19.5, languages: ["Slovak"] },
  { iso2: "SL", name: "Sierra Leone", continent: "Africa", capital: "Freetown", lat: 8.5, lng: -11.5, languages: ["English"] },
  { iso2: "SN", name: "Senegal", continent: "Africa", capital: "Dakar", lat: 14, lng: -14, languages: ["French"] },
  { iso2: "SO", name: "Somalia", continent: "Africa", capital: "Mogadishu", lat: 10, lng: 49, languages: ["Arabic","Somali"] },
  { iso2: "SOL", name: "Somaliland", continent: "Africa", capital: "Hargeisa", lat: 9.55, lng: 44.05, languages: ["Somali","Arabic"] },
  { iso2: "SR", name: "Suriname", continent: "South America", capital: "Paramaribo", lat: 4, lng: -56, languages: ["Dutch"] },
  { iso2: "SS", name: "S. Sudan", continent: "Africa", capital: "Juba", lat: 7, lng: 30, languages: ["English"] },
  { iso2: "SV", name: "El Salvador", continent: "North America", capital: "San Salvador", lat: 13.83333333, lng: -88.91666666, languages: ["Spanish"] },
  { iso2: "SY", name: "Syria", continent: "Asia", capital: "Damascus", lat: 35, lng: 38, languages: ["Arabic"] },
  { iso2: "SZ", name: "Swaziland", continent: "Africa", capital: "Lobamba", lat: -26.5, lng: 31.5, languages: ["English","Swazi"] },
  { iso2: "TD", name: "Chad", continent: "Africa", capital: "N'Djamena", lat: 15, lng: 19, languages: ["Arabic","French"] },
  { iso2: "TF", name: "Fr. S. Antarctic Lands", continent: "Seven seas (open ocean)", capital: "Port-aux-Français", lat: -49.25, lng: 69.167, languages: ["French"] },
  { iso2: "TG", name: "Togo", continent: "Africa", capital: "Lomé", lat: 8, lng: 1.16666666, languages: ["French"] },
  { iso2: "TH", name: "Thailand", continent: "Asia", capital: "Bangkok", lat: 15, lng: 100, languages: ["Thai"] },
  { iso2: "TJ", name: "Tajikistan", continent: "Asia", capital: "Dushanbe", lat: 39, lng: 71, languages: ["Russian","Tajik"] },
  { iso2: "TL", name: "Timor-Leste", continent: "Asia", capital: "Dili", lat: -8.83333333, lng: 125.91666666, languages: ["Portuguese","Tetum"] },
  { iso2: "TM", name: "Turkmenistan", continent: "Asia", capital: "Ashgabat", lat: 40, lng: 60, languages: ["Russian","Turkmen"] },
  { iso2: "TN", name: "Tunisia", continent: "Africa", capital: "Tunis", lat: 34, lng: 9, languages: ["Arabic"] },
  { iso2: "TR", name: "Turkey", continent: "Asia", capital: "Ankara", lat: 39, lng: 35, languages: ["Turkish"] },
  { iso2: "TT", name: "Trinidad and Tobago", continent: "North America", capital: "Port of Spain", lat: 11, lng: -61, languages: ["English"] },
  { iso2: "TW", name: "Taiwan", continent: "Asia", capital: "Taipei", lat: 23.5, lng: 121, languages: ["Chinese"] },
  { iso2: "TZ", name: "Tanzania", continent: "Africa", capital: "Dodoma", lat: -6, lng: 35, languages: ["English","Swahili"] },
  { iso2: "UA", name: "Ukraine", continent: "Europe", capital: "Kyiv", lat: 49, lng: 32, languages: ["Ukrainian"] },
  { iso2: "UG", name: "Uganda", continent: "Africa", capital: "Kampala", lat: 1, lng: 32, languages: ["English","Swahili"] },
  { iso2: "US", name: "United States of America", continent: "North America", capital: "Washington D.C.", lat: 38, lng: -97, languages: ["English"] },
  { iso2: "UY", name: "Uruguay", continent: "South America", capital: "Montevideo", lat: -33, lng: -56, languages: ["Spanish"] },
  { iso2: "UZ", name: "Uzbekistan", continent: "Asia", capital: "Tashkent", lat: 41, lng: 64, languages: ["Russian","Uzbek"] },
  { iso2: "VE", name: "Venezuela", continent: "South America", capital: "Caracas", lat: 8, lng: -66, languages: ["Spanish"] },
  { iso2: "VN", name: "Vietnam", continent: "Asia", capital: "Hanoi", lat: 16.16666666, lng: 107.83333333, languages: ["Vietnamese"] },
  { iso2: "VU", name: "Vanuatu", continent: "Oceania", capital: "Port Vila", lat: -16, lng: 167, languages: ["Bislama","English","French"] },
  { iso2: "XK", name: "Kosovo", continent: "Europe", capital: "Pristina", lat: 42.666667, lng: 21.166667, languages: ["Albanian","Serbian"] },
  { iso2: "YE", name: "Yemen", continent: "Asia", capital: "Sana'a", lat: 15, lng: 48, languages: ["Arabic"] },
  { iso2: "ZA", name: "South Africa", continent: "Africa", capital: "Pretoria", lat: -29, lng: 24, languages: ["Afrikaans","English","Southern Ndebele","Northern Sotho","Southern Sotho","Swazi","Tswana","Tsonga","Venda","Xhosa","Zulu"] },
  { iso2: "ZM", name: "Zambia", continent: "Africa", capital: "Lusaka", lat: -15, lng: 30, languages: ["English"] },
  { iso2: "ZW", name: "Zimbabwe", continent: "Africa", capital: "Harare", lat: -20, lng: 30, languages: ["Chibarwe","English","Kalanga","Khoisan","Ndau","Northern Ndebele","Chewa","Shona","Sotho","Tonga","Tswana","Tsonga","Venda","Xhosa","Zimbabwean Sign Language"] },
];

const byIso2 = new Map(COUNTRY_INDEX.map((c) => [c.iso2, c]));

export function findCountry(iso2: string): CountryInfo | null {
  return byIso2.get(iso2.toUpperCase()) ?? null;
}
